/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AMenuItemGroup: typeof import('ant-design-vue/es')['MenuItemGroup']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ChatBox: typeof import('./src/components/ChatBox.vue')['default']
    ChatView: typeof import('./src/views/ChatView.vue')['default']
    HomeView: typeof import('./src/views/HomeView.vue')['default']
    IconEosIconsThreeDotsLoading: typeof import('~icons/eos-icons/three-dots-loading')['default']
    IconLeLogo: typeof import('~icons/le/logo')['default']
    IconMaterialSymbolsAdd2Rounded: typeof import('~icons/material-symbols/add2-rounded')['default']
    IconMdiBrain: typeof import('~icons/mdi/brain')['default']
    IconMdiChevronDown: typeof import('~icons/mdi/chevron-down')['default']
    IconSolarAltArrowDownOutline: typeof import('~icons/solar/alt-arrow-down-outline')['default']
    IconSolarChatRoundLineOutline: typeof import('~icons/solar/chat-round-line-outline')['default']
    IconSolarCopyOutline: typeof import('~icons/solar/copy-outline')['default']
    IconSolarDislikeOutline: typeof import('~icons/solar/dislike-outline')['default']
    IconSolarLikeOutline: typeof import('~icons/solar/like-outline')['default']
    IconSolarMicrophoneLargeOutline: typeof import('~icons/solar/microphone-large-outline')['default']
    IconSolarMonitorSmartphoneBold: typeof import('~icons/solar/monitor-smartphone-bold')['default']
    IconSolarMoonFogBold: typeof import('~icons/solar/moon-fog-bold')['default']
    IconSolarPlainOutline: typeof import('~icons/solar/plain-outline')['default']
    IconSolarServerSquareCloudOutline: typeof import('~icons/solar/server-square-cloud-outline')['default']
    IconSolarStopBold: typeof import('~icons/solar/stop-bold')['default']
    IconSolarSunFogBold: typeof import('~icons/solar/sun-fog-bold')['default']
    IconSolarUnreadOutline: typeof import('~icons/solar/unread-outline')['default']
    IconSolarWidget3Outline: typeof import('~icons/solar/widget3-outline')['default']
    MarkdownRenderer: typeof import('./src/components/MarkdownRenderer.vue')['default']
    MCPStatus: typeof import('./src/components/MCPStatus.vue')['default']
    MessageActions: typeof import('./src/components/MessageActions.vue')['default']
    MessageBox: typeof import('./src/components/MessageBox.vue')['default']
    MessageItem: typeof import('./src/components/MessageItem.vue')['default']
    MessageReasoning: typeof import('./src/components/MessageReasoning.vue')['default']
    MessageToolCalls: typeof import('./src/components/MessageToolCalls.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
  }
}
