/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutView: typeof import('./src/views/AboutView.vue')['default']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuDivider: typeof import('ant-design-vue/es')['MenuDivider']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AMenuItemGroup: typeof import('ant-design-vue/es')['MenuItemGroup']
    ChatBox: typeof import('./src/components/ChatBox.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomeView: typeof import('./src/views/HomeView.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconEosIconsThreeDotsLoading: typeof import('~icons/eos-icons/three-dots-loading')['default']
    IconExample: typeof import('./src/components/IconExample.vue')['default']
    IconLeLogo: typeof import('~icons/le/logo')['default']
    IconMaterialSymbolsAdd: typeof import('~icons/material-symbols/add')['default']
    IconMaterialSymbolsAdd2Rounded: typeof import('~icons/material-symbols/add2-rounded')['default']
    IconMdiBrain: typeof import('~icons/mdi/brain')['default']
    IconMdiChat: typeof import('~icons/mdi/chat')['default']
    IconMdiChevronDown: typeof import('~icons/mdi/chevron-down')['default']
    IconSolarAddSquareOutline: typeof import('~icons/solar/add-square-outline')['default']
    IconSolarArrowToTopLeftBold: typeof import('~icons/solar/arrow-to-top-left-bold')['default']
    IconSolarChatRoundBold: typeof import('~icons/solar/chat-round-bold')['default']
    IconSolarChatRoundLineOutline: typeof import('~icons/solar/chat-round-line-outline')['default']
    IconSolarChatRoundOutline: typeof import('~icons/solar/chat-round-outline')['default']
    IconSolarDialog2Outline: typeof import('~icons/solar/dialog2-outline')['default']
    IconSolarHomeAddAngleOutline: typeof import('~icons/solar/home-add-angle-outline')['default']
    IconSolarMicrophoneBold: typeof import('~icons/solar/microphone-bold')['default']
    IconSolarMicrophoneLargeOutline: typeof import('~icons/solar/microphone-large-outline')['default']
    IconSolarMonitorSmartphoneBold: typeof import('~icons/solar/monitor-smartphone-bold')['default']
    IconSolarMoonFogBold: typeof import('~icons/solar/moon-fog-bold')['default']
    IconSolarPaletteBold: typeof import('~icons/solar/palette-bold')['default']
    IconSolarPlain2Bold: typeof import('~icons/solar/plain2-bold')['default']
    IconSolarPlainOutline: typeof import('~icons/solar/plain-outline')['default']
    IconSolarSendOutline: typeof import('~icons/solar/send-outline')['default']
    IconSolarServerSquareCloudOutline: typeof import('~icons/solar/server-square-cloud-outline')['default']
    IconSolarSettingsMinimalisticOutline: typeof import('~icons/solar/settings-minimalistic-outline')['default']
    IconSolarStopBold: typeof import('~icons/solar/stop-bold')['default']
    IconSolarStopOutline: typeof import('~icons/solar/stop-outline')['default']
    IconSolarSunFogBold: typeof import('~icons/solar/sun-fog-bold')['default']
    IconSolarWidget2Outline: typeof import('~icons/solar/widget2-outline')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    ModelSelector: typeof import('./src/components/ModelSelector.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeDemo: typeof import('./src/components/ThemeDemo.vue')['default']
    ThemeExample: typeof import('./src/components/ThemeExample.vue')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
