/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutView: typeof import('./src/views/AboutView.vue')['default']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomeView: typeof import('./src/views/HomeView.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconExample: typeof import('./src/components/IconExample.vue')['default']
    IconLeLogo: typeof import('~icons/le/logo')['default']
    IconSolarMonitorSmartphoneBold: typeof import('~icons/solar/monitor-smartphone-bold')['default']
    IconSolarMoonFogBold: typeof import('~icons/solar/moon-fog-bold')['default']
    IconSolarSunFogBold: typeof import('~icons/solar/sun-fog-bold')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeDemo: typeof import('./src/components/ThemeDemo.vue')['default']
    ThemeExample: typeof import('./src/components/ThemeExample.vue')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
